### ISSUE TITLE
Debugging issue with sriov-cni

### ISSUE THREAD

**Issue by subrnath** [Intel-Corp/sriov-cni#12]
We have created Custom Resource Definition for the K8S object "Network" and we use the sriov-cni plugin in the Network definition file.

1) Issue with the SRIOV plugin is that in case there is a mistake in Parent interface ( or Physical function ) definition as shown in "if0" below or similar mistake, POD comes up fine but no VF will be allocated to POD. it's difficult to debug the issue in this scenario as "journalctl -e" doesn't show any related error messages from sriov-cni. Is there any log files generated by it which can be used to find out the error messages ? 

apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: sriov-ipds-external1
plugin: sriov
args: '[
                {
                "name": "sriov-ipds-external1",
                "type": "sriov",
                "if0": "eno1",
                "vlan": 1925,
                "dpdk": {
                        "kernel_driver":"ixgbevf",
                        "dpdk_driver":"igb_uio",
                        "dpdk_tool":"/var/lib/docker/dpdk-devbind.py"
                }
        }

]'

2) Along with this, there is another issue where if there is a mistake in VF creation and POD is deployed with sriov plugin, subsequent POD termination reboots the underlying server.

**Comment by rkamudhan** [comment]
As for as the coding is concern, https://github.com/Intel-Corp/sriov-cni/blob/master/sriov/sriov.go#L313

if `IF0` is not there, then SRIOV CNI should throw the error. Can you please send me, your `/etc/cni/net.d` directory content. There is possibility that your kubelet is picking different conf files instead of multus confs. I have seen this in various users deployment.

**Comment by subrnath** [comment]
1. Here is our /etc/cni/net.d content
10-multus.conf
{
  "name": "multus-cni-network",
  "type": "multus",
  "kubeconfig": "/etc/kubernetes/kubelet.conf",
"delegates": [
    {
      "type": "flannel",
      "masterplugin": true,
      "delegate": {
        "isDefaultGateway": true
      }
    }
  ]
}
Point which we are trying to highlight over here is, if there is some mistake in the sriov network definition file ( e.g. different scenarios as mentioned earlier like sriov network definition doesn't exist or interface wrong etc), POD comes up with the default flannel interface. That's expected as in 10-multus.conf, thats our default configuration. But as there is no error thrown and no related logs in "journalctl -e", it's difficult to debug the issue.  So our question is - is there any log files where we can check what went wrong with SRIOV plugin,

**Comment by rkamudhan** [comment]
@subrnath We planned to do log in Multus, we discussed the proposal in details during the kubernetes Network plumbing working group. You will see this features soon in the meta plugin - https://github.com/intel/multus-cni/tree/dev/network-plumbing-working-group-crd-change

**Comment by rkamudhan** [comment]
This branch will merged to the multus master soon...

**Comment by subrnath** [comment]
OK. Thanks. I am closing the ticket now.
